alibaba:
  qwen-plus-2025-07-28:
    name: 通义千问Plus
    provider: alibaba
    model_name: qwen-plus-2025-07-28
    api_key: sk-282660fdc8cc4460943f2da2a86d3d01
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    max_tokens: 8192
    temperature: 0.7
    top_p: 0.8
    timeout: 60
    max_retries: 3
    stream: true
    enabled: true
    description: 阿里通义千问 Plus 中文对话模型
    tags:
    - chinese
    - general
    - multimodal
  qwen3-coder-plus:
    name: 通义千问 Coder
    provider: alibaba
    model_name: qwen3-coder-plus
    api_key: sk-282660fdc8cc4460943f2da2a86d3d01
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    max_tokens: 8192
    temperature: 0.7
    top_p: 0.8
    timeout: 60
    max_retries: 3
    stream: true
    enabled: true
    description: 阿里通义千问 Coder 中文对话模型
    tags:
    - chinese
    - code
深度求索:
  deepseek-chat:
    name: DeepSeek Chat
    provider: deepseek
    model_name: deepseek-chat
    api_key: sk-de5a1965cfa94ccea0eaad15d93251dc
    base_url: https://api.deepseek.com/v1
    max_tokens: 4096
    temperature: 0.7
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
    timeout: 60
    max_retries: 3
    stream: true
    enabled: true
    description: DeepSeek Chat 中文优化对话模型
    tags:
    - chinese
    - chat
    - reasoning
moonshot:
  moonshot-v1-8k:
    name: moonshot-v1-8k
    provider: moonshot
    model_name: moonshot-v1-8k
    api_key: sk-5IPFajDv6yy8hWKd3DScOHea2HE10r1FTN6SMgz038ljsSTf
    base_url: https://api.moonshot.cn/v1
    max_tokens: 8192
    temperature: 0.7
    top_p: 0.7
    timeout: 60
    max_retries: 3
    stream: true
    enabled: true
    description: 月之暗面通用大模型
    tags:
    - chinese
    - general
Ollama:
  qwen3:8b:
    name: qwen3-8b
    provider: ollama
    model_name: qwen3:8b
    api_key: sk-ollamakey123
    base_url: http://localhost:11434/v1
    max_tokens: 4096
    temperature: 0.7
    top_p: 0.9
    timeout: 120
    max_retries: 3
    stream: true
    enabled: true
    description: 本地部署的 qwen3 8B 模型
    tags:
    - local
    - qwen
    - opensource
  deepseek-r1:8b:
    name: deeseek-8b
    provider: ollama
    model_name: deepseek-r1:8b
    api_key: sk-ollamakey123
    base_url: http://localhost:11434/v1
    max_tokens: 4096
    temperature: 0.7
    top_p: 0.9
    timeout: 120
    max_retries: 3
    stream: true
    enabled: true
    description: 本地部署的 deepseek 8B 模型
    tags:
    - local
    - deepseek
    - opensource
  qwen2.5:latest:
    name: qwen2.5-8b
    provider: ollama
    model_name: qwen2.5:latest
    api_key: sk-ollamakey123
    base_url: http://localhost:11434/v1
    max_tokens: 4096
    temperature: 0.7
    top_p: 0.9
    timeout: 120
    max_retries: 3
    stream: true
    enabled: true
    description: 本地部署的 deepseek 8B 模型
    tags:
    - local
    - deepseek
    - opensource
defaults:
  timeout: 60
  max_retries: 3
  stream: true
  temperature: 0.7
  top_p: 1.0
  max_tokens: 4096
  enabled: true
metadata:
  version: 1.0.0
  created_at: '2025-01-01'
  description: LLM 模型统一配置文件
  supported_providers:
  - deepseek
  - alibaba
  - moonshot
  - ollama
doubao:
  deepseek-v3-1-terminus:
    name: 豆包DeepSeek
    base_url: https://ark.cn-beijing.volces.com/api/v3
    api_key: dac7e1c4-6883-4d14-98ba-29ab70e924cf
    timeout: 60
    max_retries: 3
    stream: true
    enabled: true
    description: ''
zhipu:
  glm-4.5-flash:
    name: GLM-4.5-Flash
    base_url: https://open.bigmodel.cn/api/paas/v4/
    api_key: 8741dc327c45445d83c82aca7e636842.H1wbh0PglthU51cQ
    timeout: 60
    max_retries: 3
    stream: true
    enabled: true
    description: ''
